# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=20)),
                ('points', models.FloatField()),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('hid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('points', models.FloatField()),
                ('starts_price', models.IntegerField()),
                ('comments_count', models.IntegerField()),
                ('noise', models.IntegerField(default=0)),
                ('air_quality', models.IntegerField(default=0)),
                ('light', models.IntegerField(default=0)),
                ('temperature', models.IntegerField(default=0)),
                ('traffic', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
