# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0003_hotel_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='starts_price',
            new_name='start_price',
        ),
    ]
