# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0004_auto_20170501_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='id',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
