# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0005_auto_20170502_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='comments_count',
            new_name='points_count',
        ),
    ]
