# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0006_auto_20170502_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
