# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0007_hotel_comments_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
