# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0008_auto_20170502_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
